#!/bin/sh
# Name : KitStart
# Date : April 2022
# Description : KitStart is a tools Starter.
# |
nc="\033[00m"
white="\033[1;37m"
grey="\033[0;37m"
purple="\033[0;35m"
red="\033[1;31m"
green="\033[32m"
yellow="\033[33m"
purple="\033[0;35m"
cyan="\033[1;36m"
cafe="\033[1;33m"
fiuscha="\033[0;35m"
blue="\033[34m"
orange="\033[38;5;122m"
# |
RED="$(printf '\033[31m')"
GREEN="$(printf '\033[32m')"
ORANGE="$(printf '\033[33m')"
BLUE="$(printf '\033[34m')"
MAGENTA="$(printf '\033[35m')"
CYAN="$(printf '\033[36m')"
WHITE="$(printf '\033[37m')"
BLACK="$(printf '\033[30m')"
REDBG="$(printf '\033[41m')"
GREENBG="$(printf '\033[42m')"
ORANGEBG="$(printf '\033[43m')"
BLUEBG="$(printf '\033[44m')"
MAGENTABG="$(printf '\033[45m')"
CYANBG="$(printf '\033[46m')"
WHITEBG="$(printf '\033[47m')"
BLACKBG="$(printf '\033[40m')"
RESETBG="$(printf '\e[0m')"
BLINK="$(printf '\033[5;31m')"
# |
Banner(){
  echo "$BLUE
   ██████   █████                  ████
  ░░██████ ░░███                  ░░███
   ░███░███ ░███   ██████   █████  ░███   ██████
   ░███░░███░███  ███░░███ ███░░   ░███  ███░░███
   ░███ ░░██████ ░███████ ░░█████  ░███ ░███████
   ░███  ░░█████ ░███░░░   ░░░░███ ░███ ░███░░░
   █████  ░░█████░░██████  ██████  █████░░██████$RED
  ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
  ▒         ▀▀█▀▀ █▀▀█ █▀▀█ █   █▀▀             ▒
  ▒           █   █  █ █  █ █   ▀▀█             ▒
  ▒           ▀   ▀▀▀▀ ▀▀▀▀ ▀▀▀ ▀▀▀$ORANGE v0.0.0.9    ▒
  ▒ https://www.github.com/Anlominus/KitStart   ▒
  ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
        One place for All Anlominus Tools
  "
}
logo="$(Banner)"

PromptFun(){
  echo ""
  echo "  ${orange}  ┌──[${blue}Anlominus${purple}👽${red}KitStart${cyan}$~${orange}]${cyan}"
  echo "  ${orange}  └──╼${green}"
}
prompt="$(PromptFun)"

installAnlominusKits(){
  echo "${yellow} [!] ${GREEN} Installing Anlominus Kits"
  echo " "
  echo " "
  echo "${yellow} [!] ${orange} Copy: WorKing Repo"
  sleep 1
  git clone https://github.com/Anlominus/WorKing.git
  echo "${yellow} [!] ${orange} Copy: HacKing Repo"
  sleep 1
  git clone https://github.com/Anlominus/HacKing.git
  echo "${yellow} [!] ${orange} Copy: AnyGen Repo"
  sleep 1
  git clone https://github.com/Anlominus/AnyGen.git
  echo "${yellow} [!] ${orange} Copy: AnyPhishing Repo"
  sleep 1
  git clone https://github.com/Anlominus/AnyPhishing.git
  echo "${yellow} [!] ${orange} Copy: PenTest Repo"
  sleep 1
  git clone https://github.com/Anlominus/PenTest.git
  echo "${yellow} [!] ${orange} Copy: AnySpam Repo"
  sleep 1
  git clone https://github.com/Anlominus/AnySpam.git
  echo "${yellow} [!] ${orange} Copy: HacKits Repo"
  sleep 1
  git clone https://github.com/Anlominus/HacKits.git
  echo "${yellow} [!] ${orange} Copy: FrameWorks Repo"
  sleep 1
  git clone https://github.com/Anlominus/FrameWorks.git
  echo "${yellow} [!] ${orange} Copy: CheatSheets Repo"
  sleep 1
  git clone https://github.com/Anlominus/CheatSheets.git
  echo "${yellow} [!] ${orange} Copy: AntiPorn Repo"
  sleep 1
  git clone https://github.com/Anlominus/AntiPorn.git
  sudo chmod -R +x ./*
}

# this is the main function
menu() {
  while true; do
    clear
    echo "$logo"
    echo " "
    echo "${green}     [g] ${GREEN}Get ${orange}Anlominus ${ORANGE}Kits"
    echo " "
    echo "${green}     [1] ${GREEN}WorKing"
    echo "${green}     [2] ${REDBG}${orange}Hac${WHITE}King${nc}"
    echo "${green}     [3] ${orange}Any${ORANGE}Gen"
    echo "${green}     [4] ${orange}Any${ORANGE}Phishing"
    echo "${green}     [5] ${MAGENTA}Pen${blue}Test"
    echo "${green}     [6] ${orange}Any${RED}Spam"
    echo "${green}     [7] ${orange}Frame${GREEN}Works"
    echo "${green}     [8] ${orange}Hac${ORANGE}Kits"
    echo "${green}     [9] ${orange}Cheat${orange}Sheets"
    echo "${green}     [10] ${white}Anti${cyan}porn"
    echo " "
    echo "${green}     [x] ${green} Exit"
    echo "$prompt"
    read cmd
    case ${cmd} in
      g)
      installAnlominusKits
      ;;
      1)
      cd WorKing
      sh WorKing start
      cd ..
      ;;
      2)
      cd HacKing
      sh HacKing start
      cd ..
      ;;
      3)
      cd AnyGen
      sh AnyGen start
      cd ..
      ;;
      4)
      cd AnyPhishing
      sh AnyPhishing start
      cd ..
      ;;
      5)
      cd PenTest
      sh PenTest start
      cd ..
      ;;
      6)
      cd AnySpam
      sh AnySpam start
      cd ..
      ;;
      7)
      cd FrameWorks
      sh FrameWorks start
      cd ..
      ;;
      8)
      cd HacKits
      sh HacKits start
      cd ..
      ;;
      9)
      cd CheatSheets
      sh CheatSheets start
      cd ..
      ;;
      10)
      cd AntiPorn
      sh AntiPorn start
      cd ..
      ;;
      x|exit|Exit)
      echo "${green}Exiting ....${nc}"
      break
      ;;
      *)
        echo "${red}${cmd}: ${purple}invalid option!!${nc}"
        sleep 1
      ;;
    esac
  done
}

# cli mode
if [ $# -eq 1 ]; then
  case $1 in
    start)
      menu
    ;;
    help|-h)
      echo "${yellow}KitStart ${red} v0.1"
      echo "${nc}Usage ${nc}: ${yellow} KitStart ${nc}[option]... [toolname]...${nc}"
      echo "\n  ${blue}Option  \tDescription${nc}"
      echo "  -----------  \t--------------------"
      echo "  start  \tstart KitStart menu mode."
    ;;
    *)
      echo "${red}Sorry ${nc}: '$1' ${red} invalid option!!${nc}"
      echo "${blue}type ${nc}:\n  'KitStart -h' or 'KitStart help' for help.${nc}"
    ;;
  esac
elif [ $# -eq 2 ]; then
  case $1 in
    *)
      echo "${red}Sorry ${nc}: '$1' ${red} invalid option!!${nc}"
      echo "${blue}type ${nc}:\n  'KitStart -h' or 'KitStart help' for help.${nc}"
    ;;
  esac
else
  echo "${blue}type ${nc}:\n  'KitStart -h' or 'KitStart help' for help.${nc}"
fi
